patchedDependencies:
  splitpanes: patches/splitpanes.patch
catalogs:
  build:
    execa: ^9.6.0
    fast-glob: ^3.3.3
    rehype-external-links: ^3.0.0
    unocss: ^66.4.2
  dev:
    '@antfu/eslint-config': ^5.2.1
    '@intlify/eslint-plugin-vue-i18n': ^4.1.0
    '@unocss/eslint-plugin': ^66.4.2
    eslint: ^9.34.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.9.2
  front:
    '@shikijs/monaco': ^3.12.0
    '@volar/monaco': ^1.11.1
    '@vue/language-service': ^1.8.25
    '@vueuse/core': ^13.8.0
    '@webcontainer/api': ^1.6.1
    '@xterm/addon-fit': ^0.10.0
    '@xterm/xterm': ^5.5.0
    birpc: ^2.5.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    jszip: ^3.10.1
    monaco-editor: ^0.45.0
    monaco-editor-core: ^0.45.0
    pathe: ^2.0.3
    pinia: ^3.0.3
    shiki: ^3.12.0
    splitpanes: 3.1.5
    strip-json-comments: ^5.0.3
    theme-vitesse: ^1.0.0
    vue: ^3.5.20
    vue-router: ^4.5.1
  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/catppuccin': ^1.2.16
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/svg-spinners': ^1.2.4
  nuxt:
    '@nuxt/content': ^3.6.3
    '@nuxt/eslint': ^1.9.0
    '@nuxtjs/color-mode': 3.5.2
    '@nuxtjs/i18n': ^10.0.6
    '@nuxtjs/seo': ^3.1.0
    '@pinia/nuxt': ^0.11.2
    '@unocss/extractor-mdc': ^66.4.2
    '@unocss/nuxt': ^66.4.2
    '@vueuse/nuxt': ^13.8.0
    nuxt: ^4.0.3
onlyBuiltDependencies:
  - better-sqlite3
